version: "0.2"
language: en
ignorePaths:
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/backend/src/taskqueue/proto/gen/**"
  - "**/.git/**"
  - "**/__pycache__/**"
  - "**/.mypy_cache/**"
  - "**/*.pyc"
  - "**/package-lock.json"
  - "**/*.egg-info/**"
words:
  - Abhinav
  - aiohttp
  - aiokafka
  - Anand
  - asyncio
  - asyncpg
  - autoprefixer
  - autouse
  - boltdb
  - configmap
  - confluentinc
  - dataclass
  - dotenv
  - enqueue
  - errno
  - esac
  - fetchrow
  - fetchval
  - grafana
  - GroupCoordinator
  - grpc
  - grpcio
  - healthcheck
  - host-gateway
  - ingester
  - inmemory
  - Iproto
  - isready
  - jsdom
  - kafka
  - kubectl
  - kvstore
  - lifecycler
  - load_dotenv
  - logql
  - loki
  - mypy
  - nextjs
  - opentelemetry
  - otel
  - podman
  - postcss
  - postgres
  - postgresql
  - prometheus
  - protobuf
  - protoc
  - psql
  - pycache
  - pyproject
  - pyright
  - pyrightconfig
  - pytest
  - PYTHONPATH
  - PYTHONUNBUFFERED
  - recharts
  - redis
  - servicer
  - setex
  - setuptools
  - shellcheck
  - stdlib
  - structlog
  - tailwindcss
  - taskqueue
  - taskqueue_pb2
  - taskqueue_pb2_grpc
  - taskqueue-pb2
  - testpaths
  - tids
  - tsx
  - venv
  - zookeeper
